AWSTemplateFormatVersion: '2010-09-09'
Description: Developer access to ExampleCompany

Parameters: 
  SSOInstanceARN: 
    Type: String 
    Description: SSO instance ARN


Resources:
  ExampleCompanyDeveloper:
    Type: AWS::SSO::PermissionSet
    Properties: 
      Description: Developer Access - (Medium Level Access)
      InstanceArn: !Ref SSOInstanceARN
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      InlinePolicy: |-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
                "Sid": "ACMDeployAccess",
                "Effect": "Allow",
                "Action": "acm:*",
                "Resource": "*"
            },
            {
                "Sid": "Dynamo",
                "Effect": "Allow",
                "Action": "dynamodb:*",
                "Resource": "*"
            },
            {
                "Sid": "lambda",
                "Effect": "Allow",
                "Action": "lambda:*",
                "Resource": "*"
            }
          ]
        }
      Name: ExampleCompanyDeveloper
      SessionDuration: "PT1H"
      Tags: 
      - Key: "AppID"
        Value: "1"
      - Key: "Classification"
        Value: "Confidential"
      - Key: "SupportTeam"
        Value: "devops@examplecompany.io"



  


